### ISSUE TITLE
【2019-04-03】用一些办法，画一个五角星

### ISSUE THREAD

**Issue by Pearyman** [moving-space/Fe-Space#17]
这个在平常还是比较常见的，例如各类的评分装置等等。

**Comment by Pearyman** [comment]
今天这个问题这么简单都没人答么？

--------

⭐️

**Comment by Pearyman** [comment]
```html
<div></div>
```

```css
div { 
  margin: 250px auto;  /*定位使用*/
  width: 0px; 
  height: 0px; 
  border-right: 100px solid transparent; 
  border-bottom: 70px solid #333; 
  border-left: 100px solid transparent; 
  -moz-transform: rotate(35deg); 
  -webkit-transform: rotate(35deg); 
  -ms-transform: rotate(35deg); 
  -o-transform: rotate(35deg); 
  transform: rotate(35deg);
  position: relative;
}
 div:before { 
  content: ''; 
  height: 0; 
  width: 0; 
  border-bottom: 80px solid #333; 
  border-left: 30px solid transparent; 
  border-right: 30px solid transparent; 
  -webkit-transform: rotate(-35deg); 
  -moz-transform: rotate(-35deg); 
  -ms-transform: rotate(-35deg); 
  -o-transform: rotate(-35deg); 
  transform: rotate(-35deg); 
  position: absolute; 
  top: -45px; 
  left: -65px; 
}  
div:after { 
  content: ''; 
  width: 0px; 
  height: 0px; 
  border-right: 100px solid transparent; 
  border-bottom: 70px solid #333; 
  border-left: 100px solid transparent; 
  -webkit-transform: rotate(-70deg); 
  -moz-transform: rotate(-70deg); 
  -ms-transform: rotate(-70deg); 
  -o-transform: rotate(-70deg);
  transform: rotate(-70deg);
  position: absolute; 
  top: 3px; 
  left: -105px; 
} 



```
